### PR TITLE
Remove all stomp packages

### PR DESCRIPTION
**Pull request by gavanderhoorn**
Preparation for migration to [ros-industrial/stomp_ros](https://github.com/ros-industrial/stomp_ros) (which is currently also a prototype).

Note: removing these pkgs without updating the rest and/or the Travis config will make CI fail - as `stomp_moveit` is a `build_depend`/`run_depend` of some of the other packages.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@jrgnicho: :bellhop_bell:

**Comment by jrgnicho** [comment]
This is pretty straight forward, the only package that needs stomp_moveit is `industrial_moveit_benchmarking`.  I can think of three ways to deal with this
1. Remove/disable the [stomp benchmarking code](https://github.com/ros-industrial/industrial_moveit/blob/melodic-devel/industrial_moveit_benchmarking/src/stomp_valgrind.cpp) altogether and call it a day.  
2. Move `stomp_valgrind.cpp` into the stomp_moveit package 
3. Have `industrial_moveit `clone the new `stomp_ros` repo as part of the CI process, not sure how to set this up but it won't require any code changes other than the CI script.  

I'm leaning more towards option I because it is the path of least resistance but option 3 feels to  me like the proper way to address it.

**Comment by gavanderhoorn** [comment]
Option 3 would be nice and isn't that difficult. See [here](https://github.com/ros-industrial/staubli_experimental/blob/f031913d8d73ba20c66159aea2f669e03ddd2479/.travis.yml) for an example Travis config that does the same thing. It uses [this file](https://github.com/ros-industrial/staubli_experimental/blob/f031913d8d73ba20c66159aea2f669e03ddd2479/.travis.rosinstall) to clone an additional (unreleased in this case) repository as part of the CI run.

If/when `industrial_moveit` gets released the dependencies of `industrial_moveit_benchmarking` will get resolved and as `stomp_ros` will be released things should-just-work.

**Comment by gavanderhoorn** [comment]
@jrgnicho: would you want me to update the PR to include the proposed change to the Travis config?

**Comment by gavanderhoorn** [comment]
Btw: as soon as `stomp_ros` is released -- and `.deb`s are available -- we wouldn't need the source-clone of `stomp_ros` as part of the Travis config. It would just be temporary.

**Comment by gavanderhoorn** [comment]
Just removed the 'draft' from this PR to get Travis to run. Let's see whether a80b9dd works as intended.

---

It didn't, so I pused b1a3fb6.

**Comment by gavanderhoorn** [comment]
@jrgnicho: seems Travis approves.

**Comment by gavanderhoorn** [comment]
One thing left to discuss is whether all the stomp test packages should be left here, migrated to `stomp_ros` as well, or whether we should create a `stomp_ros_test` repository to host them.

**Comment by jrgnicho** [comment]
@gavanderhoorn thanks for addressing the travis ci.  As far as the stomp test packages go, I don't have a strong opinion on where they should go but I lean more towards keeping them in the same repository.

**Review by jrgnicho — APPROVED** [review]

**Comment by simonschmeisser** [comment]
one of the mesh files (menger_cube.stl) is huge (20mb), if that is really needed it might make sense to have it in a separate repo

**Comment by jrgnicho** [comment]
@simonschmeisser good catch, it looks like that mesh is associated with custom urdf versions used in the [industrial_moveit_benchmarking](https://github.com/ros-industrial/industrial_moveit/blob/melodic-devel/industrial_moveit_benchmarking/src/stomp_valgrind.cpp#L61) package.  So it doesn't need to  be in the stomp repo.  We could just move the custom urdfs and STL files into the benchmarking package and update the path variables accordingly.

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn thanks for addressing the travis ci. As far as the stomp test packages go, I don't have a strong opinion on where they should go but I lean more towards keeping them in the same repository.

Moving them to a separate repository makes releasing slightly easier (no need to specify *which* packages should be included in a release, and test pkgs typically don't get released).

Using the same 'trick' as I used to get Travis working again, we can make sure that tests are also always run by Travis, even if the pkgs are hosted in a separate repository.

Are you worried about tests getting out-of-sync with the main development repository if we split them off?

**Comment by gavanderhoorn** [comment]
> @simonschmeisser good catch, it looks like that mesh is associated with custom urdf versions used in the [industrial_moveit_benchmarking](https://github.com/ros-industrial/industrial_moveit/blob/melodic-devel/industrial_moveit_benchmarking/src/stomp_valgrind.cpp#L61) package. So it doesn't need to be in the stomp repo. We could just move the custom urdfs and STL files into the benchmarking package and update the path variables accordingly.

If we want to move things around, I'd suggest doing that *before* we migrate stuff to `stomp_ros`.

@jrgnicho: could you submit a/some PR(s) to update the location of the files that should not be in the `stomp_*` packages?

I'll sync this PR after you've done that, and `stomp_ros`.

**Comment by jrgnicho** [comment]
@gavanderhoorn  sounds goood, I'll submit a PR with those changes.

**Comment by gavanderhoorn** [comment]
I'll wait for additional PRs from @jrgnicho before updating this one.

**Comment by jrgnicho** [comment]
@gavanderhoorn PR #88 has been created.

**Comment by gavanderhoorn** [comment]
@jrgnicho: I've reinitialised [ros-industrial/stomp_ros](https://github.com/ros-industrial/stomp_ros) with the current state of `melodic-devel` and then removed all non-STOMP packages.

I've also retriggered Travis to run for this PR (previous run failed because I was setting up `stomp_ros` at the exact time Travis tried to clone it).

Can you check you're comfortable with the current state of both `industrial_moveit` and `stomp_ros`?

**Comment by jrgnicho** [comment]
The [doxygen.config](https://github.com/ros-industrial/industrial_moveit/blob/a161fb75a813da33d41db67091e72322f2f6c3fb/doxygen.config#L746) file contains references to stomp packages

**Comment by jrgnicho** [comment]
Other than that I'm happy with the state of the new stomp ros repo.

**Comment by gavanderhoorn** [comment]
> The [doxygen.config](https://github.com/ros-industrial/industrial_moveit/blob/a161fb75a813da33d41db67091e72322f2f6c3fb/doxygen.config#L746) file contains references to stomp packages

Yes, good catch.

You're a maintainer too right? you can add commits to the PR ;)

**Comment by gavanderhoorn** [comment]
Doxygen addressed, Travis is OK as well.

**Review by jrgnicho — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Was no longer WIP.

**Pull request merged**
