### PR TITLE
Rename test packages

### PR DESCRIPTION
**Pull request by jrgnicho**
This is related to #86
Renames all non-stomp-critical test packages to more generic names.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Travis is happy enough, but running the `run_tests` target locally on a workspace with this PR results in this:

```
Warnings   << constrained_ik:make /catkin_ws/logs/constrained_ik/build.make.001.log
[ERROR] [1554321877.188181817]: Null pointer to JointModelGroup
[ERROR] [1554321877.297322523]: Number of joint angles (6) don't match robot_model (0)
[ERROR] [1554321877.297605521]: Number of joint angles (0) don't match robot_model (6)
[ERROR] [1554321877.297666982]: Number of joint angles (99) don't match robot_model (6)
[ERROR] [1554321877.298283265]: BasicKin not initialized in linkTransforms()
[ERROR] [1554321877.298345284]: BasicKin not initialized in linkTransforms()
[ERROR] [1554321877.298376154]: BasicKin not initialized in linkTransforms()
[ERROR] [1554321877.298416802]: BasicKin not initialized in linkTransforms()
[ERROR] [1554321877.298449418]: BasicKin not initialized in linkTransforms()
[ERROR] [1554321877.298502638]: Number of joint angles (0) don't match robot_model (6)
[ERROR] [1554321877.298532041]: BasicKin checkJoints failed in linkTransforms()
[ERROR] [1554321877.298570733]: Number of joint angles (99) don't match robot_model (6)
[ERROR] [1554321877.298597203]: BasicKin checkJoints failed in linkTransforms()
[ERROR] [1554321877.298655312]: Joint 0 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.298688277]: Joint 1 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.298718798]: Joint 2 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.298749249]: Joint 3 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.298779420]: Joint 4 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.298811059]: Joint 5 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.298837459]: BasicKin checkJoints failed in linkTransforms()
[ERROR] [1554321877.299033574]: Failed to calculate FK for joint 6
[ERROR] [1554321877.299094197]: Failed to calculate FK for joint 1
[ERROR] [1554321877.389424718]: failure at pose 5
[ERROR] [1554321877.466279635]: Number of joint angles (0) don't match robot_model (6)
[ERROR] [1554321877.466328803]: Number of joint angles (99) don't match robot_model (6)
[ERROR] [1554321877.466363584]: Joint 0 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.466391661]: Joint 1 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.466416455]: Joint 2 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.466441458]: Joint 3 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.466465553]: Joint 4 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.466490557]: Joint 5 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.642987429]: Number of joint angles (0) don't match robot_model (6)
[ERROR] [1554321877.643032127]: Number of joint angles (99) don't match robot_model (6)
[ERROR] [1554321877.643076616]: Joint 0 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.643115169]: Joint 1 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.643140661]: Joint 2 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.643166992]: Joint 3 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.643192973]: Joint 4 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.643218674]: Joint 5 is out-of-range (-6.28319 < 1e+10 < 6.28319)
[ERROR] [1554321877.810529827]: Empty matrices not supported in solvePinv()
[ERROR] [1554321877.810581091]: Matrix size mismatch: A(6,3), b(1)
```

All in `constrained_ik` though, so I'm not particularly worried about this.

**Review by gavanderhoorn — APPROVED** [review]
Approving this under the assumption that you've verified things still work (I can't test the `.launch` files right now).

**Comment by gavanderhoorn** [comment]
Thanks @jrgnicho.

With this PR merged, I believe we are in a good state to update #86, would you agree?

**Comment by jrgnicho** [comment]
@gavanderhoorn Those error messages probably merit a closer look, but since don't break the ci I'll just create an issue for now.  Thanks for the review

**Comment by gavanderhoorn** [comment]
My apologies btw, I merged this out of habit. Should've let you do that.

**Pull request merged**
