### PR TITLE
Indigo devel improvements

### PR DESCRIPTION
**Pull request by jrgnicho**
This PR contains numerous improvements to the CLIK and STOMP planners.  @Levi-Armstrong please review

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
General observation: could just be unfortunate sampling, but it looks like the code is rather sparingly commented ([here](https://github.com/ros-industrial/industrial_moveit/pull/24/files#diff-4b30385cc4e452d6114c8165b161bb59) and [here](https://github.com/ros-industrial/industrial_moveit/pull/24/files#diff-9c2f4178bec2094482cb951436826843) fi).

Would it be an idea to add some more to document the rationales?

**Comment by jrgnicho** [comment]
@gavanderhoorn these collision classes you pointed out were added in order to circumvent certain issues in the CollisionWorldFCL and CollisionRobotFCL classes in the moveit core library. We plan to submit a PR into moveit  that will address these issues; once those changes get merged we'll then use the collision library in moveit  but in the mean time we chose to use our own custom collision classes.  Thus we thought that it wasn't worth documenting this custom collision code since it will eventually go away.  @Levi-Armstrong do you have any thoughts on this?

**Comment by Levi-Armstrong** [comment]
@jrgnicho that is correct. There is an error in the distanceCallback function [here](https://github.com/ros-planning/moveit_core/issues/258). Also we needed to expose more of FCL to be able to return not only the distance but the two points used to calculate the distance.

**Comment by jrgnicho** [comment]
@Levi-Armstrong ping

**Comment by Levi-Armstrong** [comment]
+1 ready to be merge.

**Pull request merged**
