### PR TITLE
Added industrial moveit meta-package

### PR DESCRIPTION
**Pull request by shaun-edwards**

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@dpsolomon remember to change/remove your email address.  Once this is merged it will be indexed by the wiki.

**Comment by dpsolomon** [comment]
I'm thinking about changing the email addresses to <author email="dso___on@swri.org">Dan Solomon</author> so that it is human interpretable but not spam-bot friendly. I can merge it, pull/change/push it, or is there a better way to merge on the command line?

**Comment by gavanderhoorn** [comment]
> @dpsolomon remember to change/remove your email address. Once this is merged it will be indexed by the wiki.

@shaun-edwards: is this something we should do for all ROS-I packages? I haven't noticed any spam (yet).

**Comment by gavanderhoorn** [comment]
Perhaps we should submit an enhancement request for the wiki: instead of inserting all email addresses plain text, use some kind of (javascript) obfuscation system.

---

Edit: done, see ros-infrastructure/roswiki#74.

**Pull request merged**
