### PR TITLE
Changed industrial_moveit_test_support license from TODO to Apache 2.0 in package.xml

### PR DESCRIPTION
**Pull request by DavidMerzJr**
Addresses #94 , related to https://github.com/ros-industrial/ros_industrial_issues/issues/57

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@DavidMerzJr: github doesn't appear to recognise the email address you used for the commit.

Would that be something you'd want to fix (ie: change the `COMMITTER` and/or `AUTHOR` email) before this gets merged?

Alternatively you could register the email address with GH.

**Comment by gavanderhoorn** [comment]
:bellhop_bell:

**Comment by DavidMerzJr** [comment]
Sorry for the delay.  I have edited the author name.

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
I'll leave it to @jrgnicho to merge -- seeing as he is the maintainer here.

**Comment by gavanderhoorn** [comment]
@jrgnicho: could you merge this?

**Review by jrgnicho — APPROVED** [review]

**Comment by jrgnicho** [comment]
@DavidMerzJr thanks for the contribution
@gavanderhoorn thanks for reviewing

**Comment by gavanderhoorn** [comment]
Thanks @jrgnicho :+1:

**Pull request merged**
