### PR TITLE
For porting STOMP into moveIt and removing industrial_collision_detection package

### PR DESCRIPTION
**Pull request by raghavendersahdev**
This PR addresses the following:

- [ ] removed the `industrial_collision_detection` package as that is already a part of MoveIt.
- [ ] ignored the `constraint_ik` and `industrial_moveit_benchmarking` package as currently `industrial_moveit` does not build successfully when these packages are present.
- [ ] removed the `stomp_moveit` and `stomp_plugin` packages as they could be put in the moveIt planners alongside other moveit planners like CHOMP, OMPL, SBPL.

Advantages of having STOMP as a part of MoveIt:
-  **All planners at [one place](https://github.com/ros-planning/moveit/tree/kinetic-devel/moveit_planners):** It would be great to have multiple planners available in moveIt so users have a variety of motion planners (CHOMP, OMPL, STOMP, SBPL) to choose from.
- **Bug Fixing:** easier to fix bugs if MoveIt API changes.
- **moveit dependent code in moveit:** only `stomp_moveit` and `stomp_plugin` have been merged and moved to moveIt as these have a lot of dependency on moveIt code, the core STOMP code (`stomp_core` package) is still available in ros-industrial
- **standardized benchmarking for all planners:** some benchmarks can be programmed for moveIt planners using which users can validate different motion planners available in moveIt and decide which planners works best in a particular environment as there is no one standard planner that works in all types of environments.
- **STOMP MoveIt tutorial:** there is also a STOMP moveit tutorial [here](https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/stomp_planner/stomp_planner_tutorial.rst).
@davetcoleman @mamoll 
Looking forward for some feedback from ros-industrial

### CODE REVIEW

**Comment by mamoll** [comment]
@raghavendersahdev has done this work as part of his 2018 Google Summer of Code project, mentored by Dave Coleman and myself. Hopefully, ROS-Industrial can continue development and maintenance of the ROS-independent STOMP core library. I assume this is still used within Tesseract? As Raghavender mentions, this PR is part of an effort to add the MoveIt-dependent part of STOMP into the Moveit repository, so that it can become a "first-class citizen": easily available for any MoveIt user and integrated into tutorials, examples, benchmarks, etc.

**Comment by davetcoleman** [comment]
Thanks for this PR @raghavendersahdev 

Concerning:
>  ignored the constraint_ik and industrial_moveit_benchmarking package as currently industrial_moveit does not build successfully when these packages are present.

Can you document you temporarily disabled this near the top of this repo's README.md file?

@Levi-Armstrong et al I would recommend we then rename this repo ``stomp``, ``stomp_planner`` or something similar.

**Comment by raghavendersahdev** [comment]
sure @davetcoleman I have documented the temporary disabled behavior of the unused packages in the README.md file.

**Comment by jrgnicho** [comment]
@raghavendersahdev thanks for your contribution, I'll make time to review your PR next week.

**Comment by jrgnicho** [comment]
Replaced by #77

**Pull request closed without merging**
